### ISSUE TITLE
你好，能否提供数据区存储的技巧？

### ISSUE THREAD

**Issue by kn007** [zengzhan/qqzeng-ip#7]
我自己做的文件很大，因为数据区没有压缩。

数据区，像本库早期版本或纯真，都是通过flag或者说是个mode来控制重定向。

但新版，是直接通过位置和长度，就读出完整内容，而且文件还要小。

关于这块方法，方便透露吗？

谢谢。

**Comment by zengzhan** [comment]
参考一下 这里的数据结构  https://github.com/zengzhan/qqzeng-ip/blob/master/qqzeng-ip-dat  谢谢

**Comment by kn007** [comment]
你好，恕我愚笨。结构都明白，也有看过，给了很多思路跟帮助。
但就是数据区过大，不明白为什么，明明我也用了UTF16 Little Endian（莫非操作有问题。。。）去转换数据区，再把二进制数据写入文件，但还是很大（可以说跟原始大小没太大区别），不知道要怎么去压缩。。

**Comment by kn007** [comment]
我已经自己弄明白了，打扰了。

**Comment by kn007** [comment]
@zengzhan 你好，再请教一个疑问，用Little-Endian的目的在哪？
我测试了下Big-Endian和Little-Endian的速度差异并不大啊。。。

**Comment by zengzhan** [comment]
整数在内存中存储的顺序，现在 Little Endian 比较普遍

**Comment by kn007** [comment]
哦，好的，谢谢解答。
