### ISSUE TITLE
golang 3.0报错

### ISSUE THREAD

**Issue by xiaoyanchun** [zengzhan/qqzeng-ip#8]
=== RUN   TestLoad
Test Load IP Dat ...
--- FAIL: TestLoad (0.00s)
panic: runtime error: index out of range [recovered]
        panic: runtime error: index out of range

for k := 0; k < 256; k++ {
		i := k*8 + 4
		p.prefStart[k] = ReadLittleEndian32(data[i], data[i+1], data[i+2], data[i+3])
		p.prefEnd[k] = ReadLittleEndian32(data[i+4], data[i+5], data[i+6], data[i+7])
}

p.prefStart[k] = ReadLittleEndian32(data[i], data[i+1], data[i+2], data[i+3])
这行报错

**Comment by zengzhan** [comment]
已修正
